## Assignment 1 - All About torch.Tensor

An short introduction about PyTorch and about the chosen functions. 

- torch.tensor()
- torch.from_numpy()
- torch.rand()
- torch.mean()
- torch.linspace(

Before we begin, let's install and import PyTorch

In [2]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
 #!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [3]:
# Import torch and other required modules
import torch
import numpy as np

## Function 1 - torch.tensor 

 The torch.tensor() function is used to create a multi-dimensional array or tensor.

 Parameters:

    data   : The input data to create the tensor. It can be a list, tuple, Numpy array, scalar, 
             or another tensor-like object.

    dtype  : The desired data type of the tensor. If not provided, PyTorch will infer the data 
             type from the input data.

    device : The device on which the tensor will be stored. It can be a CPU or a specific GPU. 
            If not provided, the tensor will be created on the default device.

    requires_grad : If set to True, the tensor will track operations on it to enable automatic 
                   differentiation for gradient computation. This is used for training deep l l 
                  learning models. By default, it is set to False.

In [6]:
# Example 1 
t=torch.tensor([[1, 2], [3, 4.]])

In [10]:
t.size()

torch.Size([2, 2])

This create a tensor with shape(2,2)

In [11]:
# Example 2 
t2=torch.tensor([])
t2
t2.size()

torch.Size([0])

Create an empty tensor with size(0)

In [12]:
# Example 3 
torch.tensor([[1, 2], [3, 4, 5]])

ValueError: expected sequence of length 2 at dim 1 (got 3)

It is impossible to create tensor with improper shape

We can use torch.tensor() to create multidimensional tensor 

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [13]:
import jovian

In [14]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "praveenamuthukumar2511/01-tensor-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/praveenamuthukumar2511/01-tensor-operations


'https://jovian.com/praveenamuthukumar2511/01-tensor-operations'

## Function 2 - torch.from_numpy

The torch.from_numpy() function takes a NumPy array (ndarray) as input and returns a PyTorch tensor.
Parameters:

    ndarray: The NumPy array from which the tensor will be created.

In [21]:
# Example 1 
numpy_array = np.array([1, 2, 3, 4, 5])
torch_tensor = torch.from_numpy(numpy_array)
print(torch_tensor)

tensor([1, 2, 3, 4, 5])


A Numpy array has been converted into pytorch tensor by using this function.

In [22]:
# Example 2 
torch_tensor[0] = 10
print(torch_tensor)
print(numpy_array)

tensor([10,  2,  3,  4,  5])
[10  2  3  4  5]


In [23]:
# Example 3 
a2=np.array(['1','2','3'])
torch.from_numpy(a2)

TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

A Numpy array containing  string elements cannot be converted to tensor.The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.


It shows the interoperability of different python libraries

In [1]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "praveenamuthukumar2511/01-tensor-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/praveenamuthukumar2511/01-tensor-operations


'https://jovian.com/praveenamuthukumar2511/01-tensor-operations'

## Function 3 - tensor.unbind

The unbind function refers to splitting a tensor along a specified dimension into a list of tensors, where each tensor represents a slice along that dimension.

In [4]:
# Example 1 

tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
slices = torch.unbind(tensor, dim=0)
for slice in slices:
    print(slice)


tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([7, 8, 9])


Return tensor of slices with 0-dimension

In [6]:
# Example 2
t1=torch.randn(3,3)
t1.unbind()


(tensor([-0.3006, -2.5974, -1.6622]),
 tensor([-1.4173, -0.2123, -0.8321]),
 tensor([-0.9634,  0.1936, -1.1262]))

We get 3 slices of the tensor in the tuple

In [7]:
# Example 3 
t2=torch.randn(3,2)
t2.unbind(dim=2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

We created a tensor of 2 dimension then to unbind  dimension 2 is not valid .In this case,it returns Dimension out of range(Index Error)

In case ,We need to work on slices of data along the dimension of tensor,we use this function

In [9]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "praveenamuthukumar2511/01-tensor-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/praveenamuthukumar2511/01-tensor-operations


'https://jovian.com/praveenamuthukumar2511/01-tensor-operations'

## Function 4 - torch.rand()

The torch.rand() function  is used to generate random numbers from a uniform distribution between 0 and 1.

In [10]:
# Example 1 
random_tensor = torch.rand(2, 3)
print(random_tensor)

tensor([[0.3563, 0.1962, 0.0764],
        [0.3484, 0.9315, 0.7074]])


This will output a random tensor with values between 0 and 1,

In [11]:
# Example 2 
torch.rand(9)

tensor([0.1174, 0.1810, 0.4811, 0.8238, 0.0997, 0.2426, 0.6543, 0.5867, 0.0274])

In [14]:
# Example 3 
torch.rand(0,)

tensor([])

This function can be used when we want tensor with random values.

Closing comments about when to use this function

In [15]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "praveenamuthukumar2511/01-tensor-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/praveenamuthukumar2511/01-tensor-operations


'https://jovian.com/praveenamuthukumar2511/01-tensor-operations'

## Function 5 - torch.linspace()

The torch.linspace() function in PyTorch is used to generate a tensor with values evenly spaced between a start and end point. It takes three arguments: start, end, and steps.

In [16]:
# Example 1 
tensor = torch.linspace(0, 1, 5)
print(tensor)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


It generates a tensor with 5 equally spaced values between 0 and 1.

In [18]:
# Example 2 
torch.linspace(-20,10,20,dtype=torch.int)

tensor([-20, -18, -16, -15, -13, -12, -10,  -8,  -7,  -5,  -3,  -2,   0,   0,
          2,   4,   5,   6,   8,  10], dtype=torch.int32)

We get the elements that are of type int32.

In [19]:
# Example 3 
t=torch.ones((1,13))
torch.linspace(-11,7,13,out=t,dtype=torch.int32)

RuntimeError: dtype Int does not match dtype of out parameter (Float)

It is used to create data in the form of tensors ,when we know that the real data lies in particular interval

In [20]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "praveenamuthukumar2511/01-tensor-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/praveenamuthukumar2511/01-tensor-operations


'https://jovian.com/praveenamuthukumar2511/01-tensor-operations'

## Conclusion

Here,we have some basic functions which relate to some core concept of pytorch tensor like:

    . How to create tensor
    . How to modify numpy array into pytorch tensor
    . How to slices tensor with given dimension
    . How to genaerate a random tensor
    . How to create tensor with the elements that are equally spaced.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* https://jovian.com/outlink?url=https%3A%2F%2Fpytorch.org%2Fdocs%2Fstable%2Ftorch.html

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>